### ISSUE TITLE
Can't edit posts in SS4

### ISSUE THREAD

**Issue by asecondwill** [silverstripe/silverstripe-blog#493] opened 2017-12-14 16:41 UTC
The cursor changes on hover, but clicking doesn't open the post edit screen

my modules are:

```
        "silverstripe/recipe-plugin": "^1",
        "silverstripe/recipe-cms": "1.0.0@stable",
        "dnadesign/silverstripe-elemental": "2.x-dev",
        "silverstripe/elemental-blocks": "1.0.x-dev",
        "dnadesign/silverstripe-elemental-userforms": "1.x-dev",
        "dnadesign/silverstripe-elemental-list": "^1.0@dev",
        "heyday/silverstripe-menumanager": "~3.0.0",
        "silverstripe/blog": "3.0.0-alpha1"
```

**Comment by robbieaverill** [comment] 2017-12-18 04:15
Thanks for reporting. We'll be looking at getting the blog module to beta soon.

**Comment by asecondwill** [comment] 2017-12-19 21:36
Do you know when this might happen?

**Comment by robbieaverill** [comment] 2017-12-19 21:55
Probably in the few weeks after the holiday break, unless someone in the community wants to look and it and make a pull request before we get to it ;)

**Comment by asecondwill** [comment] 2017-12-21 11:15
ok, cool. thanks.   i'd love to, but probably beyond my skills, plus , tis the season for stupid deadlines : )

**Comment by asecondwill** [comment] 2017-12-21 11:25
in case anybody else finds this an issue in the meantime, I'm working around it using - 

https://github.com/jonom/silverstripe-betternavigator/tree/4.0.0

which allows nav to post in front end, then click edit

**Comment by raissanorth** [comment] 2018-01-25 23:35
I am using `3.0.x-dev` and can't reproduce the error. The edit button appears fine:

![image.png](https://images.zenhubusercontent.com/5a16269b8a75884b9088859e/267095e1-fbf4-44b1-93bf-a4cb90bb75c0)

Can you please confirm @asecondwill that this is still an issue for you? Thanks.

**Comment by robbieaverill** [comment] 2018-01-26 00:42
Thanks for trying to reproduce this @raissanorth! I'll close this for now. @asecondwill feel free to reopen the issue if you're still having problems with it (ensure you update your dependencies!)

**Comment by asecondwill** [comment] 2018-03-14 11:24
Hi,  I updated my dependancies for blog 

"silverstripe/blog": "3.*",

which installs 3.0.0

the problem persists. Ill try again next new project.

**Comment by dhensby** [comment] 2018-03-14 14:19
@asecondwill can you try to provide us with some consistent steps to reproduce this, please?

**Comment by asecondwill** [comment] 2018-04-16 16:46
I tried it today using a fresh install.  Same issue.  no edit button. 

Steps

````
composer create-project silverstripe/installer . 4.1.0   
# run though visual installer.  login to admin
composer require silverstripe/blog
php vendor/silverstripe/framework/cli-script.php dev/build
# create new blog, create new blog post.  hover over it to get edit button.  see no edit button.
<img width="1462" alt="screen shot 2018-04-16 at 17 43 51" src="https://user-images.githubusercontent.com/156546/38823358-223a95f8-419e-11e8-9b88-dca5adcd7e81.png">

**Comment by asecondwill** [comment] 2018-04-16 16:47
thats using firefox 58

**Comment by asecondwill** [comment] 2018-04-16 16:49
composer.lock for details

````
{
    "name": "silverstripe/installer",
    "type": "silverstripe-recipe",
    "description": "The SilverStripe Framework Installer",
    "require": {
        "php": ">=5.6.0",
        "silverstripe/recipe-plugin": "^1",
        "silverstripe/recipe-cms": "1.1.0@stable",
        "silverstripe-themes/simple": "~3.2.0",
        "silverstripe/blog": "^3.1"
    },
    "require-dev": {
        "phpunit/phpunit": "^5.7"
    },
    "extra": {
        "branch-alias": {
            "4.x-dev": "4.2.x-dev",
            "dev-master": "5.x-dev"
        },
        "project-files-installed": [
            "mysite/.htaccess",
            "mysite/_config.php",
            "mysite/_config/mysite.yml",
            "mysite/code/Page.php",
            "mysite/code/PageController.php"
        ],
        "public-files-installed": [
            ".htaccess",
            "index.php",
            "install-frameworkmissing.html",
            "install.php",
            "web.config"
        ]
    },
    "config": {
        "process-timeout": 600
    },
    "prefer-stable": true,
    "minimum-stability": "dev"
}
````

**Comment by asecondwill** [comment] 2018-04-16 17:46
I also tried this on 4.0.3 to see if it was todo with some issues I had with the new "public" folder in 4.1.0 but same issue.

**Comment by NightJar** [comment] 2018-04-17 23:05
@asecondwill can you please use your browser's developer tools and inform us if you're seeing any 404 responses in the network tab?
I too use Firefox and cannot replicate this issue.

I feel as if there's something not exposing as an asset at install time.

**Comment by NightJar** [comment] 2018-04-18 00:42
Oh, I lied, sorry. Looking in the wrong place.
Not a firefox issue.
Is an issue.

**Comment by asecondwill** [comment] 2018-04-19 10:49
Yep sorry should have said, no 404's.  Which makes sense if the class is missing.

**Comment by robbieaverill** [comment] 2018-04-20 04:10
PR at https://github.com/silverstripe/silverstripe-lumberjack/pull/79

**Comment by robbieaverill** [comment] 2018-04-20 04:52
I'm lying, this was actually fixed in https://github.com/silverstripe/silverstripe-lumberjack/pull/70

**Closed by robbieaverill** 2018-04-20 04:52 UTC
Labels: affects/v4, change/patch, effort/medium, impact/high, type/bug

**Comment by asecondwill** [comment] 2018-05-02 10:47
confirmed, thanks @robbieaverill
