### ISSUE TITLE
Tags and categories moved along post when moving post from one blog to another

### ISSUE THREAD

**Issue by clodeindustrie** [silverstripe/silverstripe-blog#546] opened 2018-07-29 17:23 UTC
Sorry for the massive title.

When moving a post from one blog to another, the tags and categories of that post, seem to change ownership and become part of the destination blog.

They still stay attached to other post from the origin blog though.

**Comment by raissanorth** [comment] 2018-08-23 21:25
Thanks for reporting this @clodeindustrie. Could you please let us know which version of `silverstripe-blog` you are using, thanks.

**Comment by raissanorth** [comment] 2018-09-06 23:31
Hi @clodeindustrie,

thanks for your response.

I tried recreating this with 
```
silverstripe/blog                  3.0.0  
silverstripe/cms                   4.1.0
silverstripe/lumberjack            2.0.1
silverstripe/tagfield              2.0.0   
silverstripe/assets                1.1.0   
silverstripe/asset-admin           1.1.0  

```
but unfortunately could not reproduce. 

Steps taken:

1. I created two Blog sites, Blog 1 and Blog 2. 
2. I then created Blog Post A nested under Blog 1 and Blog Post B nested under Blog 2. 
3. Following that I assigned three categories and tags to Blog Post A. 
4. For the last step I moved Blog Post A to Blog 2 _and published it_. 

--> All of the categories and tags 'stayed' with Blog Post A. Blog Post B still had no categories nor tags associated with it. 

I have confirmed this in the CMS, frontend, and database. 

I'll close this for now, but if you continue to encounter this issue @clodeindustrie, please feel free to reopen (with another comment and steps to reproduce). Thanks!

**Closed by raissanorth** 2018-09-06 23:31 UTC
Labels: affects/v4, change/patch, effort/easy, impact/medium, type/bug
