### ISSUE TITLE
Require TagField 1.1.x for SS 3.2 compatibility

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-blog#300] opened 2015-10-13 02:15 UTC
Installing this module with SilverStripe 3.2 does not currently work, because it installs a version of TagField that is not compatible with it. So please make packagist require a later version of it.

**Comment by kinglozzer** [comment] 2015-10-13 08:29
Closing this it’s (kind of) a duplicate of #293

**Closed by kinglozzer** 2015-10-13 08:29 UTC

**Comment by kinglozzer** [comment] 2015-10-13 08:38
@JorisDebonnet Fixed in 2.1.0 :)
