### ISSUE TITLE
RSS Widget depreciation notice - Simplepie

### ISSUE THREAD

**Issue by MattyBalaam** [silverstripe/silverstripe-blog#94] opened 2013-06-29 14:50 UTC
Using php 5.4.4 and ss3.1 I get the following error:

[Deprecated] Assigning the return value of new by reference is deprecated

It is calling in an older version SimplePie from Framework/ThirdParty, if I replace with a newer version it seems to work. Do you think I should open a ticket on the Framework to update, or would it be better to include a newer version in the blog module?

**Comment by assertchris** [comment] 2015-04-14 07:16
Duplicate of https://github.com/silverstripe/silverstripe-blog/issues/66

**Closed by assertchris** 2015-04-14 07:16 UTC
