### ISSUE TITLE
Extra icons in add category and tag button

### ISSUE THREAD

**Issue by satrun77** [silverstripe/silverstripe-blog#735] opened 2023-12-18 23:38 UTC
In the latest version add category and tag buttons with invalid layout.

<img width="644" alt="Screenshot 2023-12-19 at 12 19 54 PM" src="https://github.com/silverstripe/silverstripe-cms/assets/166450/546119d4-93b9-430b-9661-83778c2c68f6">

What should this be? no icon or with a specific icon? I think the icon should not be added. 

No icon to remove this line https://github.com/silverstripe/silverstripe-blog/blob/4/src/Forms/GridField/GridFieldAddByDBField.php#L229 

I could do PR if you advise on what its expected

## PRs
- https://github.com/silverstripe/silverstripe-blog/pull/736

**Comment by sabina-talipova** [comment] 2023-12-18 23:56
@satrun77, thank you that open this ticket.
This is a regression defect. This button should not have any icons. We will be really grateful if you help solve this issue.

**Comment by sabina-talipova** [comment] 2023-12-18 23:57
The problem is related to this issue.
https://github.com/silverstripe/silverstripe-cms/issues/2885

**Comment by satrun77** [comment] 2023-12-19 00:05
PR to remove the icon attribute https://github.com/silverstripe/silverstripe-blog/pull/736

**Comment by GuySartorelli** [comment] 2023-12-20 00:02
PR merged. It'll be automatically tagged by GitHub actions.

**Closed as completed by GuySartorelli** 2023-12-20 00:02 UTC
Labels: type/bug, affects/v4, impact/low, affects/v5
