### ISSUE TITLE
Blog has to be at the top level of the Sitetree

### ISSUE THREAD

**Issue by MichaelJJames** [silverstripe/silverstripe-blog#342] opened 2015-11-27 13:53 UTC
Blog has to be at the top level of the Sitetree or it causes a redirect loop

**Comment by dhensby** [comment] 2015-11-27 14:15
Do you mean at the root of the site tree?

**Comment by MichaelJJames** [comment] 2015-11-27 14:22
Hi Dan, 

Yeah it has to be at the root

Thanks 
Michael

**Comment by jameshoward** [comment] 2016-01-05 15:19
I have a blog at a 2nd level (e.g. `/about/blog`) and it's working fine. Could it be an issue with `allowed_children` on the parent page type you're trying to add the blog to?

**Comment by tractorcow** [comment] 2016-01-06 02:14
This is probably caused by https://github.com/silverstripe/silverstripe-lumberjack/pull/13, and is fixed now with lumberjack 1.1.3.

**Closed by tractorcow** 2016-01-06 02:14 UTC
