### ISSUE TITLE
Incorrect "Published" status in Lumberjack GridField when using Fluent

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-blog#522] opened 2018-03-26 03:48 UTC
When using the Blog module together with [Fluent](https://github.com/tractorcow/silverstripe-fluent), any BlogPosts created in one locale will show up in the GridField as "Published" (or scheduled to publish) in any other locale, too. That status is not correct though, as is confirmed by going to the BlogPost's details (where everything works fine, e.g. shown as Draft until published in that locale). 

I guess this may need a 'speciale case' code block just for Fluent? In any case, those posts are not considered "Published" in other locales since they are in Draft by default, so they shouldn't be marked as Published in the list. Perhaps an extra column, or replacing the content of that column with 'Draft in this locale' or something if applicable...

**Comment by robbieaverill** [comment] 2018-03-26 03:50
Thanks for reporting. I'm going to close this as a duplicate of https://github.com/silverstripe/silverstripe-lumberjack/issues/75. We can follow discussion there =)

**Closed by robbieaverill** 2018-03-26 03:50 UTC
