### ISSUE TITLE
Error while save / save & publish - SS 3.2 RC1

### ISSUE THREAD

**Issue by creativeSynergy** [silverstripe/silverstripe-blog#293] opened 2015-09-03 17:52 UTC
Hi,

I can't save new blog posts. After adding a new post, I receive the following error while trying to save or save and publish.

> Warning at line 337 of /var/www/vhosts/domain.tld/ss-3-2/framework/forms/DropdownField.php

I'm using 
* SS 3.2 RC 1 installed in a subfolder domain.tld/ss-3-2
* Debian 8.1 with Plesk 12.5
* nginx reverse proxy
* PHP 5.6.12 as fpm served by apache
* the latest (5 minutes ago) version of silverstripe-blog

**Comment by SpiritLevel** [comment] 2015-09-24 06:34
I can confirm. I get the same warning upon creating new blog posts. 

I'm using SS 3.2.0-rc1 on Ubuntu 14.04 + LAMP and the latest silverstripe-blog from packagist. I also installed comments and widgets.

**Comment by kinglozzer** [comment] 2015-09-24 08:06
Almost certainly caused by https://github.com/silverstripe-labs/silverstripe-tagfield/pull/34. Fixed in 1.1.0 of tagfield, but we’re using `~1.0.0` which won’t use 1.1.0, perhaps we should be using `^1.0`?

**Comment by SpiritLevel** [comment] 2015-09-24 09:03
Maybe 

https://github.com/silverstripe/silverstripe-blog/issues/288

is related ?

**Comment by kinglozzer** [comment] 2015-10-13 08:38
Closed via bb9beb3953a9567859b42d96b927369ce4c85606

**Closed by kinglozzer** 2015-10-13 08:38 UTC
