### ISSUE TITLE
Cannot modify $summary_fields

### ISSUE THREAD

**Issue by wernerkrauss** [silverstripe/silverstripe-blog#390] opened 2016-03-31 10:15 UTC
Hi,

i just wanted to add an extension to BlogPost to add the authors names in the grid. Somehow this doesn't work, as lumberjack always only takes SiteTree's $summary_fields into account.

**Comment by wernerkrauss** [comment] 2016-03-31 11:10
I see two possible solutions: make the lumberjack config class configurable or extend it with an updateLumberjackGridFieldConfig method. 

I can set the summary fields directly using:

```
$summary = $config->getComponentByType('GridFieldDataColumns');
$summary->setDisplayFields(singleton('BlogPost')->summaryFields());
```

which is ok, cause we only allow children of BlogPost in the lumberjack grid.

Which solution is preferred? I can write a patch for it.

**Comment by tractorcow** [comment] 2016-04-01 01:16
The second one might be easier. ;) Just be careful that, in the odd chance that non-blogposts children are saved against the blog page, that it doesn't break.

**Comment by wernerkrauss** [comment] 2016-04-01 06:11
@micmania blog module is already using this hook to inject its own lumberjack config, but there is no way to update that config, see https://github.com/silverstripe/silverstripe-blog/blob/master/code/model/Blog.php#L538

@tractorcow you mean the updateLumberjackGridfieldConfig hook? 

In the meantime i could subclass blog config and use the injector instead, but that still feels too hacky for me.

**Comment by micmania1** [comment] 2016-04-04 01:28
@wernerkrauss you can use config to swap out the `GridFieldConfig_BlogPost` class.

```
Injector:
  GridFieldConfig_BlogPost:
    class: 'MyCustomGridFieldConfig_BlogPost'
```

**Comment by micmania1** [comment] 2016-05-30 21:41
I'm going to close this as its a duplicate of #11. If anybody want to take over that pull request please feel free to do so.

**Closed by micmania1** 2016-05-30 21:41 UTC
Labels: 2.x, duplicate, feature
