### ISSUE TITLE
Enabling Fulltext search completely breaks blog admin and pagination.

### ISSUE THREAD

**Issue by beaconcodeacademy** [silverstripe/silverstripe-blog#543] opened 2018-06-22 19:47 UTC
fresh install of silverstripe 4 on ubuntu 14.04.  Enabling fulltextsearchable in _config.php (FulltextSearchable::enable();) causes the blog entries to not show in the admin (shows as no posts) and pagination is broken in template, although looping $BlogPosts works just fine.

Also, removing FulltextSearchable::enable(); from _config doesnt restore state, the admin css is permaently buggered until FulltextSearchable::enable(); is put back into config.

Yes, I build and flush so its not that.

I've also noticed that in Blog.php

    public function getBlogPosts()   
    {
        $blogPosts = BlogPost::get()->filter('ParentID', $this->ID);
        $this->extend('updateGetBlogPosts', $blogPosts); return $blogPosts;
    }

$blogPosts->Count() returns 0
whereas doing a test of $Posts = SiteTree:get()->filter('ParentID', $this->ID)->Count(); returns the expected result

As a workaround I've removed the ->Filter() since I only have the single Blog ParentID. However this only fixes on the /Blog page not the admin grid, the admin grid still reports no posts (although searching the grid comes back with results).

To workaround so the posts show again on the admin page, i removed the filter in BlogFilter:101... 

Given my workarounds are to remove the filters being used, im going to guess enabling fulltext breaks filter from DataList somehow.. hopefully my analysis helps. Cheers.

**Comment by beaconcodeacademy** [comment] 2018-06-25 18:55
I installed my instance on ubuntu 14.04 a few days before enabling fulltext and this is my composer json for reference:


    "name": "silverstripe/installer",
    "type": "silverstripe-recipe",
    "description": "The SilverStripe Framework Installer",
    "require": {
        "php": ">=5.6.0",
        "silverstripe/recipe-plugin": "^1",
        "silverstripe/recipe-cms": "1.1.2@stable",
        "silverstripe-themes/simple": "~3.2.0",
        "silverstripe/blog": "^3.1",
        "silverstripe/widgets": "^2.0",
        "silverstripe/comments": "^3.1",
        "ezyang/htmlpurifier": "^4.10",
        "tractorcow/silverstripe-colorpicker": "4.0.*@dev"
    },
    "require-dev": {
        "phpunit/phpunit": "^5.7"
    },
    "extra": {
        "branch-alias": {
            "4.x-dev": "4.2.x-dev",
            "dev-master": "5.x-dev"
        },
        "project-files-installed": [
            "mysite/.htaccess",
            "mysite/_config.php",
            "mysite/_config/mysite.yml",
            "mysite/code/Page.php",
            "mysite/code/PageController.php"
        ],
        "public-files-installed": [
            ".htaccess",
            "index.php",
            "install-frameworkmissing.html",
            "install.php",
            "web.config"
        ]
    },
    "config": {
        "process-timeout": 600
    },
    "prefer-stable": true,
    "minimum-stability": "dev"
}

**Comment by NightJar** [comment] 2018-06-26 02:17
Thanks @beaconcodeacademy - but I'm also interested in the versions of blog's dependencies you have installed:

https://github.com/silverstripe/silverstripe-blog/blob/3.1/composer.json#L12-L15

(as I suspect this may be to do with `lumberjack`)

**Comment by beaconcodeacademy** [comment] 2018-06-26 14:08
colymba/gridfield-bulk-editing-tools 3.0.0-beta4        SilverStripe GridField component to upload images/files a...
composer/ca-bundle                   1.1.1              Lets you find a path to the system CA bundle, and include...
composer/installers                  v1.5.0             A multi-framework Composer library installer
doctrine/instantiator                1.1.0              A small, lightweight utility to instantiate objects in PH...
embed/embed                          v3.3.5             PHP library to retrieve page info using oembed, opengraph...
ezyang/htmlpurifier                  v4.10.0            Standards compliant HTML filter written in PHP
guzzlehttp/psr7                      1.4.2              PSR-7 message implementation that also provides common ut...
intervention/image                   2.4.2              Image handling and manipulation library with support for ...
league/flysystem                     1.0.45             Filesystem abstraction: Many filesystems, one API.
m1/env                               2.1.2              Env is a lightweight library bringing .env file parser co...
marcj/topsort                        1.1.0              High-Performance TopSort/Dependency resolving algorithm
monolog/monolog                      1.23.0             Sends your logs to files, sockets, inboxes, databases and...
myclabs/deep-copy                    1.8.1              Create deep copies (clones) of your objects
nikic/php-parser                     v3.1.5             A PHP parser written in PHP
paragonie/random_compat              v2.0.15            PHP 5.x polyfill for random_bytes() and random_int() from...
phpdocumentor/reflection-common      1.0.1              Common reflection classes used by phpdocumentor to reflec...
phpdocumentor/reflection-docblock    4.3.0              With this component, a library can provide support for an...
phpdocumentor/type-resolver          0.4.0
phpspec/prophecy                     1.7.6              Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage            4.0.8              Library that provides collection, processing, and renderi...
phpunit/php-file-iterator            1.4.5              FilterIterator implementation that filters files based on...
phpunit/php-text-template            1.2.1              Simple template engine.
phpunit/php-timer                    1.0.9              Utility class for timing
phpunit/php-token-stream             2.0.2              Wrapper around PHP's tokenizer extension.
phpunit/phpunit                      5.7.27             The PHP Unit Testing framework.
phpunit/phpunit-mock-objects         3.4.4              Mock Object library for PHPUnit
psr/cache                            1.0.1              Common interface for caching libraries
psr/container                        1.0.0              Common Container Interface (PHP FIG PSR-11)
psr/http-message                     1.0.1              Common interface for HTTP messages
psr/log                              1.0.2              Common interface for logging libraries
psr/simple-cache                     1.0.1              Common interfaces for simple caching
sebastian/code-unit-reverse-lookup   1.0.1              Looks up which function or method a line of code belongs to
sebastian/comparator                 1.2.4              Provides the functionality to compare PHP values for equa...
sebastian/diff                       1.4.3              Diff implementation
sebastian/environment                2.0.0              Provides functionality to handle HHVM/PHP environments
sebastian/exporter                   2.0.0              Provides the functionality to export PHP variables for vi...
sebastian/global-state               1.1.1              Snapshotting of global state
sebastian/object-enumerator          2.0.1              Traverses array structures and object graphs to enumerate...
sebastian/recursion-context          2.0.0              Provides functionality to recursively process PHP variables
sebastian/resource-operations        1.0.0              Provides a list of PHP built-in functions that operate on...
sebastian/version                    2.0.1              Library that helps with managing the version number of Gi...
silverstripe-themes/simple           dev-master e4b3aa2 The SilverStripe simple theme (default SilverStripe 3 theme)
silverstripe/admin                   1.1.2              SilverStripe admin interface
silverstripe/asset-admin             1.1.2              Asset management for the SilverStripe CMS
silverstripe/assets                  1.1.2              SilverStripe Assets component
silverstripe/blog                    3.1.1              A fresh take on blogging in Silverstripe set out to tackl...
silverstripe/campaign-admin          1.1.2              SilverStripe campaign admin interface
silverstripe/cms                     4.1.2              The SilverStripe Content Management System
silverstripe/comments                3.1.1              This module provides commenting functionality for Pages a...
silverstripe/config                  1.0.4              SilverStripe configuration based on YAML and class statics
silverstripe/errorpage               1.1.2              ErrorPage component for SilverStripe CMS
silverstripe/framework               4.1.2              The SilverStripe framework
silverstripe/graphql                 1.1.2              GraphQL server for SilverStripe models and other data
silverstripe/lumberjack              2.0.0              A module to make managing pages in a GridField easy witho...
silverstripe/recipe-cms              1.1.2              SilverStripe recipe for fully featured page and asset con...
silverstripe/recipe-core             1.1.2              SilverStripe framework-only core recipe
silverstripe/recipe-plugin           1.3.0              Helper plugin to install SilverStripe recipes
silverstripe/reports                 4.1.2              Reports module for SilverStripe CMS
silverstripe/siteconfig              4.1.2              Site wide settings administration.
silverstripe/tagfield                2.0.0              Tag field for Silverstripe
silverstripe/vendor-plugin           1.3.3              Allows vendor modules to expose directories to the webroot
silverstripe/versioned               1.1.2              SilverStripe Versioned component
silverstripe/widgets                 2.0.1              Widgets are small pieces of functionality such as showing...
swiftmailer/swiftmailer              v5.4.9             Swiftmailer, free feature-rich PHP mailer
symfony/cache                        v3.4.11            Symfony Cache component with PSR-6, PSR-16, and tags
symfony/config                       v3.4.11            Symfony Config Component
symfony/filesystem                   v4.1.0             Symfony Filesystem Component
symfony/finder                       v3.4.11            Symfony Finder Component
symfony/polyfill-apcu                v1.8.0             Symfony polyfill backporting apcu_* functions to lower PH...
symfony/polyfill-ctype               v1.8.0             Symfony polyfill for ctype functions
symfony/polyfill-mbstring            v1.8.0             Symfony polyfill for the Mbstring extension
symfony/translation                  v2.8.41            Symfony Translation Component
symfony/yaml                         v3.4.11            Symfony Yaml Component
tractorcow/silverstripe-colorpicker  4.0.0              Color picker field for Silverstripe CMS using the ColorPi...
webmozart/assert                     1.3.0              Assertions to validate method input/output with nice erro...
webonyx/graphql-php                  v0.8.0             A PHP port of GraphQL reference implementation

**Comment by NightJar** [comment] 2018-06-26 21:59
Neat, thank you!

**Comment by robbieaverill** [comment] 2018-07-06 06:17
Hi @beaconcodeacademy, I can't reproduce this using your example composer.json and the following steps:

* Install site
* Open CMS
* Create a blog
* Create two blog posts under it
* Publish them all
* Add `\SilverStripe\ORM\Search\FulltextSearchable::enable()` to `mysite/_config.php`
* Flush, check frontend and backend

I will note that my frontend search doesn't work, but that's because I'm using a version of MySQL that doesn't support fulltext indexes.

I'm going to close this for now, but please feel free to reopen the issue if you are able to provide steps for us to reproduce your issue. Thanks for reporting 😃

**Closed by robbieaverill** 2018-07-06 06:17 UTC
Labels: affects/v4, change/patch, effort/medium, feedback-required/author, impact/high, type/bug

**Comment by NightJar** [comment] 2018-07-08 22:31
It may be worth noting that Ubuntu 14.04 is very old, and runs PHP 5.5.9 by default from what Google tells me. This _may_ have some impact, I'm unsure. But it's worth checking if an update or different environment (perhaps a local development [virtual] machine) sees your issue disappear :)
