### ISSUE TITLE
Umlaut in BlogCategory/-Tag/Profile throws a 404

### ISSUE THREAD

**Issue by lerni** [silverstripe/silverstripe-blog#484] opened 2017-10-17 21:16 UTC
getCurrentCategory, getCurrentTag, getCurrentProfile all use a URLSegmentFilter. 

URLSegmentExtension also uses a URLSegmentFilter in generateURLSegment and sets it to AllowMultibyte(true) but those above not. Hence a 404 it thrown say for example in:
https://github.com/silverstripe/silverstripe-blog/blob/2.4/code/model/Blog.php#L893

Wouldn't it make sense to $filter->setAllowMultibyte(true); for all of the above?

https://github.com/silverstripe/silverstripe-blog/blob/2.4/code/model/Blog.php#L711
https://github.com/silverstripe/silverstripe-blog/blob/2.4/code/model/Blog.php#L911
https://github.com/silverstripe/silverstripe-blog/blob/2.4/code/model/Blog.php#L911

Or how would you approach this? If my suggestion makes sense I'm happy to PR.

**Comment by robbieaverill** [comment] 2017-10-17 22:00
Hi @lerni, thanks for reporting.

Yeah - we've had a couple of patches go in recently for this kind of thing - perhaps haven't caught all of them yet!

The "allow multibyte" setting is configurable, and URLSegmentFilter applies it by default if it's enabled, so I don't think enabling it explicitly by default would be appropriate.

Are you experiencing this in an environment with "allow multibyte" enabled, or disabled?

If you're willing to submit a pull request, it'd be ideal if you could also provide a unit test with any code changes that exemplify the problem you're experiencing, and pass with your changes.

Cheers!

**Comment by lerni** [comment] 2017-10-17 23:00
ciao @robbieaverill
thx for answering! setting default_allow_multibyte to true per config resolves the issue with false it persists and a 404 is thrown for example on /blog/category/röbi
to be honest I won’t find the time to provide a unit test anytime soon, since I'm not familiar enough with testing. But if I get around one day the test needs to show the failure and the PR could set default_allow_multibyte: true in config.yml. Such a change could go into blog 2.5 which is probable not that likely to happen? I need it on SS 3.6.x. So it basically means if one need Umlaute in categories/tags or profile, you need to set it your self for 2.x?

**Comment by robbieaverill** [comment] 2017-10-17 23:03
@lerni 

>setting default_allow_multibyte to true per config resolves the issue with false it persists and a 404 is thrown for example on /blog/category/röbi

Ok, I think this is expected behaviour. It's up to the user to enable multibyte filtering.

>So it basically means if one need Umlaute in categories/tags or profile, you need to set it your self for 2.x?

Correct.

How does this work when compared to say the URL segments on pages in the core CMS with other locales?

**Comment by lerni** [comment] 2017-10-19 18:14
> How does this work when compared to say the URL segments on pages in the core CMS with other locales?
I have it on a site with fluent in production (de,en) - so far no problems. But if it's set per config doesn't it imply default_allow_multibyte is set to true for all projects with Blog installed? Therefor URLSegmentFilter with AllowMultibyte should be tested and that’s already covered in URLSegmentFilterTest?

Anyway I cannot judge how save it is, to enforce this with blog but I just ask myself, is it really that bad to be a bit more verbose and set it explicitly? Since this affect not just umlauts, a solution to make BlogCategory/-Tag/Profile
multibyte safe out of the box is really desirable.

**Comment by robbieaverill** [comment] 2017-10-19 20:29
@dhensby @micmania1 would one of you mind weighing in here? I assume there's a reason that `URLSegmentFilter.default_allow_multibyte` is false by default in core rather than true

**Comment by dhensby** [comment] 2017-10-20 10:49
I'm not really sure of the reasons multibyte urls aren't allowed by default :(

**Comment by robbieaverill** [comment] 2017-11-03 01:23
Ok, do we think it reasonable to enable them by default in the blog module?

**Comment by lerni** [comment] 2017-11-03 07:31
@Robbieaverill since AllowMultibyte broke blog isn't it likely to break other code as well? Can't we enable it with next major SS and in the mean time set it explicit in blog?

@tractorcow, @chillu are your thoughts about enabling AllowMultibyte by default in SS5?

**Comment by wernerkrauss** [comment] 2017-11-08 09:17
I think the problem is, that when the URLSegment is generated in https://github.com/silverstripe/silverstripe-blog/blob/2.4/code/extensions/URLSegmentExtension.php#L43 we generate it WITH multibytes allowed, but when we want to grab the result from the DB we ignore multibyte.

I'd propose to either:
* make a blog specific setting for allowing multibytes for BlogCategory etc , because I don't want multibytes in my other URLSements. 
* check for the global setting and respect it in URLSegmentExtension and the controller actions

**Comment by dhensby** [comment] 2017-11-08 11:58
> check for the global setting and respect it in URLSegmentExtension and the controller actions

I'd go for this

**Comment by lerni** [comment] 2017-11-08 12:43
From 2010 but probable still valuable per RFC 1738:
https://stackoverflow.com/questions/2742852/unicode-characters-in-urls

**Comment by robbieaverill** [comment] 2019-04-05 01:57
We've done some work on improving handling for multibyte URL segments in the blog module recently. Please feel free to reopen if this is still occurring on the latest version of SilverStripe and the blog module, but I think it should be fixed now.

**Closed by robbieaverill** 2019-04-05 01:57 UTC
Labels: affects/v3, affects/v4, change/patch, effort/medium, impact/medium, type/bug
